name: ESLint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage
      - "*dev"
      - "*qa"
    paths:
      - "client/**"
  pull_request:
    branches: "*"
    paths:
      - "client/**"

permissions:
  contents: read

jobs:
  lint:
    name: Lint Frontend Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint client/ --max-warnings 0
